### ISSUE TITLE
Dialog closes unexpectedly when any validation has failed

### ISSUE THREAD

**Issue by salvaom** [pyblish/pyblish-qml#348] opened 2019-10-21 13:46 UTC
Hello.

I'm finding that since I've last updated pyblish-qml (`1.8.7` -> `1.10.2`) I'm having this issue where if something fails to validate, the dialog closes suddenly and without explanation. If there is no validation error, it'll work just fine. I've made a couple of videos showcasing the issue:

[video1](https://drive.google.com/open?id=1_ZqWtEL2BqH4CADbIRMfer41uFc0CT8P)
[video2](https://drive.google.com/open?id=15bAc6_QCTdmH3zIAzYnvjroSM5x48FHX)

I'm using the following versions:

```
pyblish 1.8.0
pyblish_qml 1.10.2
pyQt 5.9
maya 2019.1
os Windows10
```

Has anyone experienced something similar?

**Comment by tokejepsen** [comment] 2019-10-21 13:53
Yup have experienced the same.

**Comment by davidlatwe** [comment] 2019-10-21 13:56
Hi @salvaom , you might need to provide minimum reproducible code or the error log.

What I have learnt from those two video, QML did not crash when you only run the validation, and it crash when you run publish. Is that correct ?

**Comment by salvaom** [comment] 2019-10-21 14:02
@davidlatwe [Here](https://pastebin.ubuntu.com/p/d5mkT5RFTZ/) are some logs, it's not much, so I'll try to get a repro code working and share it here.

**Comment by salvaom** [comment] 2019-10-21 14:53
@davidlatwe I'm able to reproduce with the following [snippet](https://gist.github.com/salvaom/6052d4dad0c697f8fda1ad60c99c1546)

**Comment by davidlatwe** [comment] 2019-10-21 15:18
Thanks @salvaom , I found that you are using Python 3.7 from your log, I think the reason was the same as #333.

Can you change to use Python 3.6 for a test ?

**Comment by davidlatwe** [comment] 2019-10-21 15:36
It's definitely because Python 3.7, since [PEP 479](https://www.python.org/dev/peps/pep-0479/) has been enabled in Py37.

Closing this now since this issue has been confirm as duplicated with #333.

**Closed by davidlatwe** 2019-10-21 15:36 UTC
